config/routes.rb
Rails.application.routes.draw do
  root to: "books#index"
  resources :books, only:[:show, :new, :create, :edit, :update, :destroy]
  get 'books' => "books#books" #TOP
  # get 'book/show/:id' => "books#show" #詳細画面
  # post '/book' => "books#create" #新規登録
  # get 'book/:id/edit' => "books#edit" #編集画面
  # patch 'book/:id/update' => "books#update"
  # post 'book/:id/update' => "books#update" #更新
  # delete 'book/:id' => 'books#destroy' #削除

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
    validates :title,presence: true
    validates :body,presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
  end

  def books
    @books = Book.all
    @book = Book.new
  end

  def show
    @book = Book.find(params[:id])
  end

  def edit
    @book = Book.find(params[:id])
  end
  
  def create
      @book = Book.new(book_params)
      if @book.save
        last_id = Book.last(1)
        flash[:notice] = 'Create successfully'
      redirect_to controller: :books, action: :show, id: last_id
      else
        @books = Book.all
        render template: 'books/books'
      end
  end
  
  def update
    @book = Book.find(params[:id])
    if
      @book.update(book_params)
      flash[:notice] = 'Update successfully'
      redirect_to controller: :books, action: :show, id: params[:id]
    else
      render :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path, notice: 'Delete successfully'
  end
  
  private
  def book_params
    params.require(:book).permit(:title, :body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/books/books.html.erb
<body>
    <% if flash[:notice] %>
        <div class="notice" style="color:green;"><%= flash[:notice] %></div>
    <% end %>

<h1>Books</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
  <% @books.each do |book| %>
      <tr>
        <td><%= book.title %></td>
        <td><%= book.body %></td>
        <td><%= link_to 'Show', book_path(book.id) %></td>
        <td><%= link_to 'Edit', edit_book_path(book.id) %></td>
        <td><%= link_to 'Destroy', book_path(book.id), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
      <% end %>
  </tbody>
</table>

<h2>New book</h2>

<%= form_with(model: @book, local: true) do |form| %>
  <% if @book.errors.any? %>
    <div class = "alert">
        <ul>
        <% @book.errors.full_messages.each do |message| %>
            <li style="color:red;"><%= message %></li>
        <% end %>
        </ul>
    </div>
  <% end %> 
  
  <div class="field">
    <% if @book.errors.include?(:title)%>
        <span style="color:red;"><%= form.label :title %></span>
    <% else %>
        <%= form.label :title %>
    <% end %>

    <%= form.text_field :title %>
  </div>

  <div class="field">
    <% if @book.errors.include?(:title)%>
        <span style="color:red;"><%= form.label :body %></span>
    <% else %>
        <%= form.label :body %>
    <% end %>
    
    <%= form.text_area :body %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>
  

</body>

app/views/books/edit.html.erb
<body>
    <h1>Editing Book</h1>

<%= form_with url:book_path(@book.id),model:@book ,local: true do |form|  %>
  <% if @book.errors.any? %>
    <div class = "alert">
        <ul>
        <% @book.errors.full_messages.each do |message| %>
            <li style="color:red;"><%= message %></li>
        <% end %>
        </ul>
    </div>
  <% end %> 
  
  <div class="field">
     <% if @book.errors.include?(:title)%>
        <span style="color:red;"><%= form.label :title %></span>
    <% else %>
        <%= form.label :title %>
    <% end %>

    <%= form.text_field :title ,value: @book.title%>
  </div>

  <div class="field">
     <% if @book.errors.include?(:body)%>
        <span style="color:red;"><%= form.label :body %></span>
    <% else %>
        <%= form.label :body %>
    <% end %>

    <%= form.text_area :body ,value: @book.body%>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

<%= link_to 'Show', book_path(@book.id) %> |
<%= link_to 'Back', books_path %>

  

</body>

app/views/books/index.html.erb
<h1>ようこそ <strong>Bookers</strong>  へ！</h1>
<p><strong>Bookers</strong>  では、さまざまな書籍に関するあなたの意見や</p><p>印象を共有し交換することができます</p>
<p><%= link_to 'Start', books_path %></p>

app/views/books/show.html.erb
<body>
  <% if flash[:notice] %>
    <div class="notice" style="color:green;"><%= flash[:notice] %></div>
  <% end %>

<p>
  <strong>Title:</strong>
  <%= @book.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @book.body %>
</p>

<%= link_to 'Edit', edit_book_path(@book.id) %> |
<%= link_to 'Back', books_path %>

  

</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>